# Generated by Django 4.1.4 on 2022-12-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Portafolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foto", models.TextField()),
                ("titulo_project", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("tags", models.CharField(max_length=100)),
                ("url_github", models.TextField()),
            ],
            options={
                "db_table": "portafolio",
            },
        ),
    ]
