# Generated by Django 4.1.4 on 2022-12-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portafolio", "0002_portafolio_id_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ipvisits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=20)),
                ("fecha_visita", models.DateTimeField()),
            ],
        ),
    ]
