# Generated by Django 4.1.4 on 2022-12-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portafolio", "0003_ipvisits"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="ipvisits",
            table="ipVisits",
        ),
    ]
