# Generated by Django 4.1.4 on 2022-12-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portafolio", "0004_alter_ipvisits_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ipvisits",
            name="fecha_visita",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
